[package]
name = "VideoPlayer"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.15"
symphonia = { version = "0.5", features = ["mp3", "wav", "flac", "ogg", "aac"] }


[[bin]]
name = "audio"
path = "src/audio.rs"

[[bin]]
name = "main"
path = "src/main.rs"